### ISSUE TITLE
string error

### ISSUE THREAD

**Issue by Ayush-505** [avibhawnani/MED3#1]
i am getting this error pls help -
* Invalid value undefined for HardhatConfig.networks.polygon_mumbai.url - Expected a value of type string.
  * Invalid account: #0 for network: polygon_mumbai - Expected string, received undefined

**Comment by avibhawnani** [comment]
https://ethereum.stackexchange.com/questions/112942/invalid-value-undefined-for-hardhatconfig-networks-mainnet-fork-url-expected-a
